---
name: "remote_shell_cmd"
# pack: "sensor_sample_automation" 
action_ref: "core.remote"
description: "Execute a command on a remote host via SSH"
formats: 
  - "(run|execute) {{cmd}} on {{hosts}}"
  - "Please run {{cmd}}"

parameters:
  hosts: "localhost"
  cmd: "date"
  timeout: 120


#immutable_parameters:
  #hosts: localhost
