---
name: "monitorKeyValuePairValueChange.yaml"
description: "detect when the value change" 
enabled: true

trigger: 
  type: "core.st2.key_value_pair.value_change"
  parameter: {}

action: 
  ref: "sample_sensor_automation.sayHello"
  parameters:
    message: "new value is {{st2kv.system.x}}"
   
